import os

configfile: "config.yaml"

INPUTDIR = config["input"]
RESULTSDIR = config["results"]
ADMIN_LEVEL = config["admin_level"]
ASSET_GEOMS = config["asset_geoms"]
HAZARDS = config["hazards"]
LOCAL_CRS = config["local_crs"]


include: "rules/assets.smk"
include: "rules/hazards.smk"
include: "rules/risk.smk"
