import os

configfile: "config.yaml"

INDIR = config["input"]
TMPDIR = config["temp"]
RESDIR = config["results"]
ADMIN_LEVEL = config["admin_level"]
ASSET_GEOMS = config["asset_geoms"]
HAZARDS = config["hazards"]
LOCAL_CRS = config["local_crs"]

include: "rules/assets.smk"
include: "rules/hazards.smk"
include: "rules/intersections.smk"
